FROM    node:16.14.2-alpine3.15

WORKDIR /app

COPY    package.json .
COPY    package-lock.json .

RUN     npm install

COPY    ./proto/greeting.proto .
COPY    /server/server.js .

ENTRYPOINT ["node", "server.js"]
